# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 01:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bailarines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_bailarin', models.CharField(max_length=20)),
                ('apellido_paterno_bailarin', models.CharField(max_length=20)),
                ('apellido_materno_bailarin', models.CharField(max_length=20)),
                ('edad_bailarin', models.FloatField()),
                ('curso', models.CharField(max_length=25)),
                ('horario_ensayo', models.CharField(max_length=10)),
                ('image_bailarin', models.ImageField(blank=True, upload_to='Bailarines_Image')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor_danza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('edad', models.FloatField()),
                ('especialidad', models.CharField(max_length=25)),
                ('horario_trabajo', models.CharField(max_length=10)),
                ('image_ins', models.ImageField(blank=True, upload_to='Ins_Image')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('bailarin', models.ManyToManyField(to='bases.Bailarines')),
                ('trainer_perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
