# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailarines',
            name='Instructor_danza',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
