# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0003_auto_20161014_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor_danza',
            name='nombre_bailarin',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
