# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0007_auto_20161031_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bailarines',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='instructor_danza',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
